[package]
name = "bera-reth"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
alloy-consensus = "1.0.17"
alloy-eips = "1.0.17"
alloy-genesis = "1.0.17"
alloy-primitives = "1.2.1"
alloy-rlp = "0.3.12"
alloy-rpc-types = "1.0.17"
alloy-serde = "1.0.17"
clap = { version = "4.5.40", features = ["derive"] }
derive_more = "2.0.1"
eyre = "0.6.12"
jsonrpsee-core = "0.25.1"
reth = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-ethereum-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", rev = "60940dd243918a1ba55f5cce5046a443bc75611d" }
serde = { version = "1.0", features = ["derive"], default-features = false }
thiserror = "2.0"
tracing = "0.1.41"

[features]
default = ["jemalloc"]
jemalloc = ["reth/jemalloc"]
asm-keccak = ["reth/asm-keccak"]
min-debug-logs = ["reth/min-debug-logs"]

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[profile.profiling]
inherits = "release"
debug = "full"
strip = "none"

[patch."https://github.com/paradigmxyz/reth"]
#reth = { path = "../reth/bin/reth" }
#reth-basic-payload-builder = { path = "../reth/crates/payload/basic" }
#reth-chainspec = { path = "../reth/crates/chainspec" }
#reth-cli = { path = "../reth/crates/cli/cli" }
#reth-cli-commands = { path = "../reth/crates/cli/commands" }
#reth-cli-util = { path = "../reth/crates/cli/util" }
#reth-db = { path = "../reth/crates/storage/db" }
#reth-engine-local = { path = "../reth/crates/engine/local" }
#reth-engine-primitives = { path = "../reth/crates/engine/primitives" }
#reth-ethereum-cli = { path = "../reth/crates/ethereum/cli" }
#reth-ethereum-engine-primitives = { path = "../reth/crates/ethereum/engine-primitives" }
#reth-ethereum-payload-builder = { path = "../reth/crates/ethereum/payload" }
#reth-ethereum-primitives = { path = "../reth/crates/ethereum/primitives" }
#reth-evm = { path = "../reth/crates/evm/evm" }
#reth-evm-ethereum = { path = "../reth/crates/ethereum/evm" }
#reth-network-peers = { path = "../reth/crates/net/peers" }
#reth-node-api = { path = "../reth/crates/node/api" }
#reth-node-builder = { path = "../reth/crates/node/builder" }
#reth-node-ethereum = { path = "../reth/crates/ethereum/node" }
#reth-payload-primitives = { path = "../reth/crates/payload/primitives" }
#reth-primitives-traits = { path = "../reth/crates/primitives-traits" }
#reth-tracing = { path = "../reth/crates/tracing" }
#reth-codecs = { path = "../reth/crates/storage/codecs" }
