name: Docker Nightly

on:
  schedule:
    # Run at 1:00 AM UTC every day (every 24 hours)
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  docker-nightly:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: nightly
      profile: maxperf

  docker-nightly-profiling:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: nightly-profiling
      profile: profiling
