name: Docker Git SHA

on:
  workflow_dispatch:

jobs:
  docker-git:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: ${{ github.sha }}
